### ISSUE TITLE
The app closes when tapping the "Scenario" button

### ISSUE THREAD

**Issue by kranem** [therealtimmi/GloomhavenCampaignTracker#63]
I updated the apk this morning through Google Play and when I tried to see the Scenario enhancements... Oh oh! I cannot see the scenarios anymore, the apk shuts down immediately.

**Comment by kranem** [comment]
![Screenshot_2020-04-20-08-59-13-542_com miui bugreport](https://user-images.githubusercontent.com/64025632/79776899-ab404080-82f3-11ea-91dc-6ccc3cc442db.jpg)
I took this screenshot of the error, I hope it helps

**Comment by stimm4711** [comment]
I'm aware of this issue. I received many reports on this. An update is on it's way and should be available until tomorrow.

**Comment by stimm4711** [comment]
Fixed
