### ISSUE TITLE
App closes straight away with new update on Samsung S10

### ISSUE THREAD

**Issue by sturobo** [therealtimmi/GloomhavenCampaignTracker#64]
When I open the app, I get a screen saying updating database 1.4.18, then 1.4.19 then the app closes. I've rebooted my phone but it's still  won't load.

**Comment by stimm4711** [comment]
Hi Stuart,

Could you send me a backup of your database to stimm@outlook.com<mailto:stimm@outlook.com> please?

Regards,
Stefan

Von: Stuart Robinson-Vyas<mailto:notifications@github.com>
Gesendet: Mittwoch, 22. April 2020 16:02
An: stimm4711/GloomhavenCampaignTracker<mailto:GloomhavenCampaignTracker@noreply.github.com>
Cc: Subscribed<mailto:subscribed@noreply.github.com>
Betreff: [stimm4711/GloomhavenCampaignTracker] App closes straight away with new update on Samsung S10 (#64)


When I open the app, I get a screen saying updating database 1.4.18, then 1.4.19 then the app closes. I've rebooted my phone but it's still won't load.

**Comment by sturobo** [comment]
I've sent that over by e-mail. Thanks for looking into this - the app has genuinely improved our setup/teardown!

**Comment by stimm4711** [comment]
I didn't receive an e-mail. But I will release a new update until tomorrow that hopefully will fix the bug.

**Comment by stimm4711** [comment]
Update is online. Hope it works now. Please give feedback.

**Comment by sturobo** [comment]
That's absolutely fantastic, it's working again. Once again, thanks for making such a brilliant and useful app!
