### ISSUE TITLE
Problems with adding treasures to scenarios

### ISSUE THREAD

**Issue by Fenix4k** [therealtimmi/GloomhavenCampaignTracker#66]
Hello again

We just noticed today that it seems not to be possible to add treasures to scenarios anymore.
In the lower scenarios, it seems to show them by itself, however at scenarios 100 and onwards (at least) it cannot be done anymore.

Again, thanks for all your work! using the app since beginning of 2019 and it is a huge help with organising the game!

**Comment by stimm4711** [comment]
I've added the treasures of the FC scenarios in the next update
